-- +goose Up 
INSERT INTO ingredients (id, name) VALUES ('1', 'A38');
INSERT INTO ingredients (id, name) VALUES ('2', 'Aborre');
INSERT INTO ingredients (id, name) VALUES ('3', 'Abrikos');
INSERT INTO ingredients (id, name) VALUES ('4', 'Abrikosmarmelade');
INSERT INTO ingredients (id, name) VALUES ('5', 'Agurk');
INSERT INTO ingredients (id, name) VALUES ('6', 'Ale');
INSERT INTO ingredients (id, name) VALUES ('7', 'Ananas');
INSERT INTO ingredients (id, name) VALUES ('8', 'Ananasjuice');
INSERT INTO ingredients (id, name) VALUES ('9', 'Ananaskirsebær');
INSERT INTO ingredients (id, name) VALUES ('10', 'And');
INSERT INTO ingredients (id, name) VALUES ('11', 'Ansjos');
INSERT INTO ingredients (id, name) VALUES ('12', 'Appelsin');
INSERT INTO ingredients (id, name) VALUES ('13', 'Appelsinjuice');
INSERT INTO ingredients (id, name) VALUES ('14', 'Appelsinmarmelade');
INSERT INTO ingredients (id, name) VALUES ('15', 'Artiskok');
INSERT INTO ingredients (id, name) VALUES ('16', 'Asier');
INSERT INTO ingredients (id, name) VALUES ('17', 'Asparges');
INSERT INTO ingredients (id, name) VALUES ('18', 'Aubergine');
INSERT INTO ingredients (id, name) VALUES ('19', 'Avocado');
INSERT INTO ingredients (id, name) VALUES ('20', 'Baby gulerødder');
INSERT INTO ingredients (id, name) VALUES ('21', 'Babymajs');
INSERT INTO ingredients (id, name) VALUES ('22', 'Babyspinat');
INSERT INTO ingredients (id, name) VALUES ('23', 'Bacon');
INSERT INTO ingredients (id, name) VALUES ('24', 'Bagegær');
INSERT INTO ingredients (id, name) VALUES ('25', 'Bagepulver');
INSERT INTO ingredients (id, name) VALUES ('26', 'Baked beans');
INSERT INTO ingredients (id, name) VALUES ('27', 'Bambusskud');
INSERT INTO ingredients (id, name) VALUES ('28', 'Banan');
INSERT INTO ingredients (id, name) VALUES ('29', 'Batat');
INSERT INTO ingredients (id, name) VALUES ('30', 'Bayonneskinke');
INSERT INTO ingredients (id, name) VALUES ('31', 'Birkes');
INSERT INTO ingredients (id, name) VALUES ('32', 'Bitter');
INSERT INTO ingredients (id, name) VALUES ('33', 'Bladbede');
INSERT INTO ingredients (id, name) VALUES ('34', 'Bladselleri');
INSERT INTO ingredients (id, name) VALUES ('35', 'Blandet frugt- og grøntsagsjuice');
INSERT INTO ingredients (id, name) VALUES ('36', 'Blandet frugtjuice');
INSERT INTO ingredients (id, name) VALUES ('37', 'Blandet grøntsagsjuice');
INSERT INTO ingredients (id, name) VALUES ('38', 'Blodpølse');
INSERT INTO ingredients (id, name) VALUES ('39', 'Blomkål');
INSERT INTO ingredients (id, name) VALUES ('40', 'Blomme');
INSERT INTO ingredients (id, name) VALUES ('41', 'Blåbær');
INSERT INTO ingredients (id, name) VALUES ('42', 'Blåmusling');
INSERT INTO ingredients (id, name) VALUES ('43', 'Blæksprutte');
INSERT INTO ingredients (id, name) VALUES ('44', 'Boghvede');
INSERT INTO ingredients (id, name) VALUES ('45', 'Boghvedegryn');
INSERT INTO ingredients (id, name) VALUES ('46', 'Boghvedemel');
INSERT INTO ingredients (id, name) VALUES ('47', 'Bolcher');
INSERT INTO ingredients (id, name) VALUES ('48', 'Bomuldsfrøolie');
INSERT INTO ingredients (id, name) VALUES ('49', 'Bondebrød');
INSERT INTO ingredients (id, name) VALUES ('50', 'Bouillon');
INSERT INTO ingredients (id, name) VALUES ('51', 'Brasen');
INSERT INTO ingredients (id, name) VALUES ('52', 'Brie');
INSERT INTO ingredients (id, name) VALUES ('53', 'Brisling');
INSERT INTO ingredients (id, name) VALUES ('54', 'Brissel');
INSERT INTO ingredients (id, name) VALUES ('55', 'Broccoli');
INSERT INTO ingredients (id, name) VALUES ('56', 'Brombær');
INSERT INTO ingredients (id, name) VALUES ('57', 'Brosme');
INSERT INTO ingredients (id, name) VALUES ('58', 'Brune linser');
INSERT INTO ingredients (id, name) VALUES ('59', 'Brøndkarse');
INSERT INTO ingredients (id, name) VALUES ('60', 'Buddingpulver');
INSERT INTO ingredients (id, name) VALUES ('61', 'Bulgur');
INSERT INTO ingredients (id, name) VALUES ('62', 'Butter chicken');
INSERT INTO ingredients (id, name) VALUES ('63', 'Byggryn');
INSERT INTO ingredients (id, name) VALUES ('64', 'Bygmel');
INSERT INTO ingredients (id, name) VALUES ('65', 'Bækforel');
INSERT INTO ingredients (id, name) VALUES ('66', 'Bærmix');
INSERT INTO ingredients (id, name) VALUES ('67', 'Bønnemix');
INSERT INTO ingredients (id, name) VALUES ('68', 'Bønner');
INSERT INTO ingredients (id, name) VALUES ('69', 'Bønnespirer');
INSERT INTO ingredients (id, name) VALUES ('70', 'Cacaomælk');
INSERT INTO ingredients (id, name) VALUES ('71', 'Cacaoskummetmælk');
INSERT INTO ingredients (id, name) VALUES ('72', 'Camembert');
INSERT INTO ingredients (id, name) VALUES ('73', 'Campari');
INSERT INTO ingredients (id, name) VALUES ('74', 'Cantaloupe');
INSERT INTO ingredients (id, name) VALUES ('75', 'Cashewnød');
INSERT INTO ingredients (id, name) VALUES ('76', 'Cayote');
INSERT INTO ingredients (id, name) VALUES ('77', 'Champignon');
INSERT INTO ingredients (id, name) VALUES ('78', 'Cheddar');
INSERT INTO ingredients (id, name) VALUES ('79', 'Cherimoya');
INSERT INTO ingredients (id, name) VALUES ('80', 'Cheshire');
INSERT INTO ingredients (id, name) VALUES ('81', 'Chiafrø');
INSERT INTO ingredients (id, name) VALUES ('82', 'Chilibønner');
INSERT INTO ingredients (id, name) VALUES ('83', 'Chokolade');
INSERT INTO ingredients (id, name) VALUES ('84', 'Chokolade is');
INSERT INTO ingredients (id, name) VALUES ('85', 'Chokoladeis');
INSERT INTO ingredients (id, name) VALUES ('86', 'Citron');
INSERT INTO ingredients (id, name) VALUES ('87', 'Citronsaft');
INSERT INTO ingredients (id, name) VALUES ('88', 'Citronskal');
INSERT INTO ingredients (id, name) VALUES ('89', 'Cognac');
INSERT INTO ingredients (id, name) VALUES ('90', 'Cornflakes');
INSERT INTO ingredients (id, name) VALUES ('91', 'Creme fraiche 18 %');
INSERT INTO ingredients (id, name) VALUES ('92', 'Creme fraiche 38 %');
INSERT INTO ingredients (id, name) VALUES ('93', 'Creme fraiche 50 %');
INSERT INTO ingredients (id, name) VALUES ('94', 'Croissant');
INSERT INTO ingredients (id, name) VALUES ('95', 'Daddel');
INSERT INTO ingredients (id, name) VALUES ('96', 'Danablu 50+');
INSERT INTO ingredients (id, name) VALUES ('97', 'Danablu 60+');
INSERT INTO ingredients (id, name) VALUES ('98', 'Danbo');
INSERT INTO ingredients (id, name) VALUES ('99', 'Dild');
INSERT INTO ingredients (id, name) VALUES ('100', 'Dressing');
INSERT INTO ingredients (id, name) VALUES ('101', 'Drueagurk');
INSERT INTO ingredients (id, name) VALUES ('102', 'Druesaft');
INSERT INTO ingredients (id, name) VALUES ('103', 'Due');
INSERT INTO ingredients (id, name) VALUES ('104', 'Edamamebønner');
INSERT INTO ingredients (id, name) VALUES ('105', 'Eddike');
INSERT INTO ingredients (id, name) VALUES ('106', 'Elbo');
INSERT INTO ingredients (id, name) VALUES ('107', 'Emmentaler');
INSERT INTO ingredients (id, name) VALUES ('108', 'Esrom');
INSERT INTO ingredients (id, name) VALUES ('109', 'Fasan');
INSERT INTO ingredients (id, name) VALUES ('110', 'Fennikel');
INSERT INTO ingredients (id, name) VALUES ('111', 'Fersken');
INSERT INTO ingredients (id, name) VALUES ('112', 'Feta');
INSERT INTO ingredients (id, name) VALUES ('113', 'Figen');
INSERT INTO ingredients (id, name) VALUES ('114', 'Fiskeboller');
INSERT INTO ingredients (id, name) VALUES ('115', 'Fiskefars');
INSERT INTO ingredients (id, name) VALUES ('116', 'Fiskefilet');
INSERT INTO ingredients (id, name) VALUES ('117', 'Fiskefrikadelle');
INSERT INTO ingredients (id, name) VALUES ('118', 'Fiskeolie');
INSERT INTO ingredients (id, name) VALUES ('119', 'Fiskepinde');
INSERT INTO ingredients (id, name) VALUES ('120', 'Flydende olie margarine');
INSERT INTO ingredients (id, name) VALUES ('121', 'Flæskesvær');
INSERT INTO ingredients (id, name) VALUES ('122', 'Fløde 13 %');
INSERT INTO ingredients (id, name) VALUES ('123', 'Fløde 18 %');
INSERT INTO ingredients (id, name) VALUES ('124', 'Fløde 38 %');
INSERT INTO ingredients (id, name) VALUES ('125', 'Fløde 50 %');
INSERT INTO ingredients (id, name) VALUES ('126', 'Fløde 9 %');
INSERT INTO ingredients (id, name) VALUES ('127', 'Flødeboller');
INSERT INTO ingredients (id, name) VALUES ('128', 'Flødeost');
INSERT INTO ingredients (id, name) VALUES ('129', 'Flødeskumskage');
INSERT INTO ingredients (id, name) VALUES ('130', 'Flødeyoghurt naturel');
INSERT INTO ingredients (id, name) VALUES ('131', 'Flûte');
INSERT INTO ingredients (id, name) VALUES ('132', 'Forloren skildpadde');
INSERT INTO ingredients (id, name) VALUES ('133', 'Forårsløg');
INSERT INTO ingredients (id, name) VALUES ('134', 'Forårsrulle');
INSERT INTO ingredients (id, name) VALUES ('135', 'Fransk hot dog');
INSERT INTO ingredients (id, name) VALUES ('136', 'Franskbrød');
INSERT INTO ingredients (id, name) VALUES ('137', 'Frugt smoothie');
INSERT INTO ingredients (id, name) VALUES ('138', 'Frugt- og grøntsag smoothie');
INSERT INTO ingredients (id, name) VALUES ('139', 'Frugtkvark');
INSERT INTO ingredients (id, name) VALUES ('140', 'Frugtnektar');
INSERT INTO ingredients (id, name) VALUES ('141', 'Frugtpålæg');
INSERT INTO ingredients (id, name) VALUES ('142', 'Fruktose');
INSERT INTO ingredients (id, name) VALUES ('143', 'Frølår');
INSERT INTO ingredients (id, name) VALUES ('144', 'Fynbo');
INSERT INTO ingredients (id, name) VALUES ('145', 'Fårekød');
INSERT INTO ingredients (id, name) VALUES ('146', 'Gaffelbidder');
INSERT INTO ingredients (id, name) VALUES ('147', 'Galia melon');
INSERT INTO ingredients (id, name) VALUES ('148', 'Gedde');
INSERT INTO ingredients (id, name) VALUES ('149', 'Gedemælk');
INSERT INTO ingredients (id, name) VALUES ('150', 'Gedeost');
INSERT INTO ingredients (id, name) VALUES ('151', 'Gelatine');
INSERT INTO ingredients (id, name) VALUES ('152', 'Gin');
INSERT INTO ingredients (id, name) VALUES ('153', 'Grahamsbrød');
INSERT INTO ingredients (id, name) VALUES ('154', 'Grahamsmel');
INSERT INTO ingredients (id, name) VALUES ('155', 'Grana');
INSERT INTO ingredients (id, name) VALUES ('156', 'Granatæble');
INSERT INTO ingredients (id, name) VALUES ('157', 'Granatæblekerner');
INSERT INTO ingredients (id, name) VALUES ('158', 'Grapefrugt');
INSERT INTO ingredients (id, name) VALUES ('159', 'Grapefrugtjuice');
INSERT INTO ingredients (id, name) VALUES ('160', 'Grisefedt');
INSERT INTO ingredients (id, name) VALUES ('161', 'Grisefilet');
INSERT INTO ingredients (id, name) VALUES ('162', 'Grisekød');
INSERT INTO ingredients (id, name) VALUES ('163', 'Grisespæk');
INSERT INTO ingredients (id, name) VALUES ('164', 'Grovbolle');
INSERT INTO ingredients (id, name) VALUES ('165', 'Grovfranskbrød');
INSERT INTO ingredients (id, name) VALUES ('166', 'Gruyere');
INSERT INTO ingredients (id, name) VALUES ('167', 'Græskar');
INSERT INTO ingredients (id, name) VALUES ('168', 'Græskarkerner');
INSERT INTO ingredients (id, name) VALUES ('169', 'Grønkål');
INSERT INTO ingredients (id, name) VALUES ('170', 'Grønne bønner');
INSERT INTO ingredients (id, name) VALUES ('171', 'Grønne ærter');
INSERT INTO ingredients (id, name) VALUES ('172', 'Guavabær');
INSERT INTO ingredients (id, name) VALUES ('173', 'Gule ærter');
INSERT INTO ingredients (id, name) VALUES ('174', 'Gulerod');
INSERT INTO ingredients (id, name) VALUES ('175', 'Gulerodsjuice');
INSERT INTO ingredients (id, name) VALUES ('176', 'Gulerødder');
INSERT INTO ingredients (id, name) VALUES ('177', 'Gås');
INSERT INTO ingredients (id, name) VALUES ('178', 'Gåsefedt');
INSERT INTO ingredients (id, name) VALUES ('179', 'Gær');
INSERT INTO ingredients (id, name) VALUES ('180', 'Gærekstrakt');
INSERT INTO ingredients (id, name) VALUES ('181', 'Hajmalle');
INSERT INTO ingredients (id, name) VALUES ('182', 'Hakket');
INSERT INTO ingredients (id, name) VALUES ('183', 'Hakket bolle');
INSERT INTO ingredients (id, name) VALUES ('184', 'Halve kartofler');
INSERT INTO ingredients (id, name) VALUES ('185', 'Hamburgerryg');
INSERT INTO ingredients (id, name) VALUES ('186', 'Harekød');
INSERT INTO ingredients (id, name) VALUES ('187', 'Hasselnød');
INSERT INTO ingredients (id, name) VALUES ('188', 'Havarti');
INSERT INTO ingredients (id, name) VALUES ('189', 'Havkat');
INSERT INTO ingredients (id, name) VALUES ('190', 'Havredrik');
INSERT INTO ingredients (id, name) VALUES ('191', 'Havregryn');
INSERT INTO ingredients (id, name) VALUES ('192', 'Havreklid');
INSERT INTO ingredients (id, name) VALUES ('193', 'Havtorn');
INSERT INTO ingredients (id, name) VALUES ('194', 'Hellefisk');
INSERT INTO ingredients (id, name) VALUES ('195', 'Helleflynder');
INSERT INTO ingredients (id, name) VALUES ('196', 'Helt');
INSERT INTO ingredients (id, name) VALUES ('197', 'Hestekød');
INSERT INTO ingredients (id, name) VALUES ('198', 'Hindbær');
INSERT INTO ingredients (id, name) VALUES ('199', 'Hindbærmarmelade');
INSERT INTO ingredients (id, name) VALUES ('200', 'Hindbærsaft');
INSERT INTO ingredients (id, name) VALUES ('201', 'Hirse');
INSERT INTO ingredients (id, name) VALUES ('202', 'Hirseflager');
INSERT INTO ingredients (id, name) VALUES ('203', 'Hjerte');
INSERT INTO ingredients (id, name) VALUES ('204', 'Honning');
INSERT INTO ingredients (id, name) VALUES ('205', 'Honningmelon');
INSERT INTO ingredients (id, name) VALUES ('206', 'Hornfisk');
INSERT INTO ingredients (id, name) VALUES ('207', 'Hot dog');
INSERT INTO ingredients (id, name) VALUES ('208', 'Hummer');
INSERT INTO ingredients (id, name) VALUES ('209', 'Hvalkød');
INSERT INTO ingredients (id, name) VALUES ('210', 'Hvedebrød');
INSERT INTO ingredients (id, name) VALUES ('211', 'Hvedegryn');
INSERT INTO ingredients (id, name) VALUES ('212', 'Hvedekerner');
INSERT INTO ingredients (id, name) VALUES ('213', 'Hvedekim');
INSERT INTO ingredients (id, name) VALUES ('214', 'Hvedekimolie');
INSERT INTO ingredients (id, name) VALUES ('215', 'Hvedeklid');
INSERT INTO ingredients (id, name) VALUES ('216', 'Hvedemel');
INSERT INTO ingredients (id, name) VALUES ('217', 'Hvedeøl');
INSERT INTO ingredients (id, name) VALUES ('218', 'Hvid hvede');
INSERT INTO ingredients (id, name) VALUES ('219', 'Hvid hvede bolle');
INSERT INTO ingredients (id, name) VALUES ('220', 'Hvid hvede brød');
INSERT INTO ingredients (id, name) VALUES ('221', 'Hvide bønner');
INSERT INTO ingredients (id, name) VALUES ('222', 'Hvidkål');
INSERT INTO ingredients (id, name) VALUES ('223', 'Hvidløg');
INSERT INTO ingredients (id, name) VALUES ('224', 'Hvidvin');
INSERT INTO ingredients (id, name) VALUES ('225', 'Hvilling');
INSERT INTO ingredients (id, name) VALUES ('226', 'Hyben');
INSERT INTO ingredients (id, name) VALUES ('227', 'Hyben pulver');
INSERT INTO ingredients (id, name) VALUES ('228', 'Hybensaft');
INSERT INTO ingredients (id, name) VALUES ('229', 'Hyldebær');
INSERT INTO ingredients (id, name) VALUES ('230', 'Hyldebærsaft');
INSERT INTO ingredients (id, name) VALUES ('231', 'Hytteost');
INSERT INTO ingredients (id, name) VALUES ('232', 'Høne');
INSERT INTO ingredients (id, name) VALUES ('233', 'Hønsesalat');
INSERT INTO ingredients (id, name) VALUES ('234', 'Hørfrø');
INSERT INTO ingredients (id, name) VALUES ('235', 'Hørfrøolie');
INSERT INTO ingredients (id, name) VALUES ('236', 'Ingefær');
INSERT INTO ingredients (id, name) VALUES ('237', 'Is');
INSERT INTO ingredients (id, name) VALUES ('238', 'Isbåd');
INSERT INTO ingredients (id, name) VALUES ('239', 'Ising');
INSERT INTO ingredients (id, name) VALUES ('240', 'Ispind');
INSERT INTO ingredients (id, name) VALUES ('241', 'Jagtpølse');
INSERT INTO ingredients (id, name) VALUES ('242', 'Jomfruhummer');
INSERT INTO ingredients (id, name) VALUES ('243', 'Jordbær');
INSERT INTO ingredients (id, name) VALUES ('244', 'Jordbærmarmelade');
INSERT INTO ingredients (id, name) VALUES ('245', 'Jordbærsaft');
INSERT INTO ingredients (id, name) VALUES ('246', 'Jordnød');
INSERT INTO ingredients (id, name) VALUES ('247', 'Jordnøddeolie');
INSERT INTO ingredients (id, name) VALUES ('248', 'Jordnøddesmør');
INSERT INTO ingredients (id, name) VALUES ('249', 'Jordskok');
INSERT INTO ingredients (id, name) VALUES ('250', 'Julebryg');
INSERT INTO ingredients (id, name) VALUES ('251', 'Julesalat');
INSERT INTO ingredients (id, name) VALUES ('252', 'Kaffe');
INSERT INTO ingredients (id, name) VALUES ('253', 'Kaffebønne');
INSERT INTO ingredients (id, name) VALUES ('254', 'Kage');
INSERT INTO ingredients (id, name) VALUES ('255', 'Kakao');
INSERT INTO ingredients (id, name) VALUES ('256', 'Kakaosmør');
INSERT INTO ingredients (id, name) VALUES ('257', 'Kakifrugt');
INSERT INTO ingredients (id, name) VALUES ('258', 'Kaktusfigen');
INSERT INTO ingredients (id, name) VALUES ('259', 'Kalkun');
INSERT INTO ingredients (id, name) VALUES ('260', 'Kalkunkød');
INSERT INTO ingredients (id, name) VALUES ('261', 'Kalv- og svinekød');
INSERT INTO ingredients (id, name) VALUES ('262', 'Kalvekød');
INSERT INTO ingredients (id, name) VALUES ('263', 'Kammerjunkere');
INSERT INTO ingredients (id, name) VALUES ('264', 'Kanel');
INSERT INTO ingredients (id, name) VALUES ('265', 'Kaninkød');
INSERT INTO ingredients (id, name) VALUES ('266', 'Kantarel');
INSERT INTO ingredients (id, name) VALUES ('267', 'Karameller');
INSERT INTO ingredients (id, name) VALUES ('268', 'Karry');
INSERT INTO ingredients (id, name) VALUES ('269', 'Karrysalat');
INSERT INTO ingredients (id, name) VALUES ('270', 'Karse');
INSERT INTO ingredients (id, name) VALUES ('271', 'Kartoffel');
INSERT INTO ingredients (id, name) VALUES ('272', 'Kartoffelbåde');
INSERT INTO ingredients (id, name) VALUES ('273', 'Kartoffelchips');
INSERT INTO ingredients (id, name) VALUES ('274', 'Kartoffelmel');
INSERT INTO ingredients (id, name) VALUES ('275', 'Kartoffelmos');
INSERT INTO ingredients (id, name) VALUES ('276', 'Kastanje');
INSERT INTO ingredients (id, name) VALUES ('277', 'Kaviar');
INSERT INTO ingredients (id, name) VALUES ('278', 'Kiks');
INSERT INTO ingredients (id, name) VALUES ('279', 'Kiks til ost');
INSERT INTO ingredients (id, name) VALUES ('280', 'Kikærter');
INSERT INTO ingredients (id, name) VALUES ('281', 'Kinakål');
INSERT INTO ingredients (id, name) VALUES ('282', 'Kinaradise');
INSERT INTO ingredients (id, name) VALUES ('283', 'Kirsebær');
INSERT INTO ingredients (id, name) VALUES ('284', 'Kirsebærmarmelade');
INSERT INTO ingredients (id, name) VALUES ('285', 'Kirsebærsaft');
INSERT INTO ingredients (id, name) VALUES ('286', 'Kiwi');
INSERT INTO ingredients (id, name) VALUES ('287', 'Kiwimarmelade');
INSERT INTO ingredients (id, name) VALUES ('288', 'Klipfisk');
INSERT INTO ingredients (id, name) VALUES ('289', 'Knude');
INSERT INTO ingredients (id, name) VALUES ('290', 'Knudekål');
INSERT INTO ingredients (id, name) VALUES ('291', 'Knækbrød');
INSERT INTO ingredients (id, name) VALUES ('292', 'Kogt oksebryst');
INSERT INTO ingredients (id, name) VALUES ('293', 'Kokosmel');
INSERT INTO ingredients (id, name) VALUES ('294', 'Kokosnød');
INSERT INTO ingredients (id, name) VALUES ('295', 'Kokosolie');
INSERT INTO ingredients (id, name) VALUES ('296', 'Koldskål');
INSERT INTO ingredients (id, name) VALUES ('297', 'Kommen');
INSERT INTO ingredients (id, name) VALUES ('298', 'Koncentreret blandet frugt- og bærsaft');
INSERT INTO ingredients (id, name) VALUES ('299', 'Koncentreret læskedrik');
INSERT INTO ingredients (id, name) VALUES ('300', 'Koncentreret tranebærsaft');
INSERT INTO ingredients (id, name) VALUES ('301', 'Kongeål');
INSERT INTO ingredients (id, name) VALUES ('302', 'Koriander');
INSERT INTO ingredients (id, name) VALUES ('303', 'Krabbe');
INSERT INTO ingredients (id, name) VALUES ('304', 'Krabbekløer');
INSERT INTO ingredients (id, name) VALUES ('305', 'Kransekage');
INSERT INTO ingredients (id, name) VALUES ('306', 'Krebs');
INSERT INTO ingredients (id, name) VALUES ('307', 'Krydder');
INSERT INTO ingredients (id, name) VALUES ('308', 'Krydderskinke');
INSERT INTO ingredients (id, name) VALUES ('309', 'Kråse');
INSERT INTO ingredients (id, name) VALUES ('310', 'Kuller');
INSERT INTO ingredients (id, name) VALUES ('311', 'Kulmule');
INSERT INTO ingredients (id, name) VALUES ('312', 'Kumquat');
INSERT INTO ingredients (id, name) VALUES ('313', 'Kvark');
INSERT INTO ingredients (id, name) VALUES ('314', 'Kvæde');
INSERT INTO ingredients (id, name) VALUES ('315', 'Kylling');
INSERT INTO ingredients (id, name) VALUES ('316', 'Kylling & bacon salat');
INSERT INTO ingredients (id, name) VALUES ('317', 'Kyllingekød');
INSERT INTO ingredients (id, name) VALUES ('318', 'Kyllingenuggets');
INSERT INTO ingredients (id, name) VALUES ('319', 'Kyllingepølse');
INSERT INTO ingredients (id, name) VALUES ('320', 'Kålrabi');
INSERT INTO ingredients (id, name) VALUES ('321', 'Kærnemælk');
INSERT INTO ingredients (id, name) VALUES ('322', 'Kødboller');
INSERT INTO ingredients (id, name) VALUES ('323', 'Kødekstrakt');
INSERT INTO ingredients (id, name) VALUES ('324', 'Kødpølse');
INSERT INTO ingredients (id, name) VALUES ('325', 'Kødrand');
INSERT INTO ingredients (id, name) VALUES ('326', 'Kørvel');
INSERT INTO ingredients (id, name) VALUES ('327', 'Lactose');
INSERT INTO ingredients (id, name) VALUES ('328', 'Lagerøl');
INSERT INTO ingredients (id, name) VALUES ('329', 'Lakrids');
INSERT INTO ingredients (id, name) VALUES ('330', 'Lakridskonfekt');
INSERT INTO ingredients (id, name) VALUES ('331', 'Laks');
INSERT INTO ingredients (id, name) VALUES ('332', 'Lammekød');
INSERT INTO ingredients (id, name) VALUES ('333', 'Lange');
INSERT INTO ingredients (id, name) VALUES ('334', 'Le Puy linser');
INSERT INTO ingredients (id, name) VALUES ('335', 'Letmælk');
INSERT INTO ingredients (id, name) VALUES ('336', 'Letmælkskefir');
INSERT INTO ingredients (id, name) VALUES ('337', 'Lever');
INSERT INTO ingredients (id, name) VALUES ('338', 'Leverpostej');
INSERT INTO ingredients (id, name) VALUES ('339', 'Leverpølse');
INSERT INTO ingredients (id, name) VALUES ('340', 'Levertran');
INSERT INTO ingredients (id, name) VALUES ('341', 'Likør');
INSERT INTO ingredients (id, name) VALUES ('342', 'Lime');
INSERT INTO ingredients (id, name) VALUES ('343', 'Linser');
INSERT INTO ingredients (id, name) VALUES ('344', 'Linsespirer');
INSERT INTO ingredients (id, name) VALUES ('345', 'Litchi');
INSERT INTO ingredients (id, name) VALUES ('346', 'Loganbær');
INSERT INTO ingredients (id, name) VALUES ('347', 'Lollandske rosiner');
INSERT INTO ingredients (id, name) VALUES ('348', 'Loquat');
INSERT INTO ingredients (id, name) VALUES ('349', 'Lucerne');
INSERT INTO ingredients (id, name) VALUES ('350', 'Lucernespirer');
INSERT INTO ingredients (id, name) VALUES ('351', 'Lyssej');
INSERT INTO ingredients (id, name) VALUES ('352', 'Læskedrik');
INSERT INTO ingredients (id, name) VALUES ('353', 'Løg');
INSERT INTO ingredients (id, name) VALUES ('354', 'Madeira');
INSERT INTO ingredients (id, name) VALUES ('355', 'Majroe');
INSERT INTO ingredients (id, name) VALUES ('356', 'Majs');
INSERT INTO ingredients (id, name) VALUES ('357', 'Majskimolie');
INSERT INTO ingredients (id, name) VALUES ('358', 'Majskolbe');
INSERT INTO ingredients (id, name) VALUES ('359', 'Majsmel');
INSERT INTO ingredients (id, name) VALUES ('360', 'Majsolie');
INSERT INTO ingredients (id, name) VALUES ('361', 'Majsstivelse');
INSERT INTO ingredients (id, name) VALUES ('362', 'Makaroni');
INSERT INTO ingredients (id, name) VALUES ('363', 'Makrel');
INSERT INTO ingredients (id, name) VALUES ('364', 'Malakoffpølse');
INSERT INTO ingredients (id, name) VALUES ('365', 'Mandarin');
INSERT INTO ingredients (id, name) VALUES ('366', 'Mandel');
INSERT INTO ingredients (id, name) VALUES ('367', 'Mandeldrik');
INSERT INTO ingredients (id, name) VALUES ('368', 'Mango');
INSERT INTO ingredients (id, name) VALUES ('369', 'Mangomarmelade');
INSERT INTO ingredients (id, name) VALUES ('370', 'Maniok');
INSERT INTO ingredients (id, name) VALUES ('371', 'Marcipan');
INSERT INTO ingredients (id, name) VALUES ('372', 'Marcipanprodukt');
INSERT INTO ingredients (id, name) VALUES ('373', 'Margarine');
INSERT INTO ingredients (id, name) VALUES ('374', 'Maribo');
INSERT INTO ingredients (id, name) VALUES ('375', 'Marmelade');
INSERT INTO ingredients (id, name) VALUES ('376', 'Mayonnaise');
INSERT INTO ingredients (id, name) VALUES ('377', 'Melbanan');
INSERT INTO ingredients (id, name) VALUES ('378', 'Melboller');
INSERT INTO ingredients (id, name) VALUES ('379', 'Milkshake');
INSERT INTO ingredients (id, name) VALUES ('380', 'Millionbøf');
INSERT INTO ingredients (id, name) VALUES ('381', 'Minarine');
INSERT INTO ingredients (id, name) VALUES ('382', 'Mineralvand');
INSERT INTO ingredients (id, name) VALUES ('383', 'Minimælk');
INSERT INTO ingredients (id, name) VALUES ('384', 'Mintgele');
INSERT INTO ingredients (id, name) VALUES ('385', 'Miso');
INSERT INTO ingredients (id, name) VALUES ('386', 'Modermælk');
INSERT INTO ingredients (id, name) VALUES ('387', 'Morgenmadsprodukt');
INSERT INTO ingredients (id, name) VALUES ('388', 'Mozzarella');
INSERT INTO ingredients (id, name) VALUES ('389', 'Mungbønner');
INSERT INTO ingredients (id, name) VALUES ('390', 'Muskatnød');
INSERT INTO ingredients (id, name) VALUES ('391', 'Musling');
INSERT INTO ingredients (id, name) VALUES ('392', 'Myseost');
INSERT INTO ingredients (id, name) VALUES ('393', 'Mælkebøtte');
INSERT INTO ingredients (id, name) VALUES ('394', 'Mørk hvidtøl');
INSERT INTO ingredients (id, name) VALUES ('395', 'Mørksej');
INSERT INTO ingredients (id, name) VALUES ('396', 'Müsli');
INSERT INTO ingredients (id, name) VALUES ('397', 'Müslibar');
INSERT INTO ingredients (id, name) VALUES ('398', 'Nektarin');
INSERT INTO ingredients (id, name) VALUES ('399', 'Netmelon');
INSERT INTO ingredients (id, name) VALUES ('400', 'Nougat');
INSERT INTO ingredients (id, name) VALUES ('401', 'Nyre');
INSERT INTO ingredients (id, name) VALUES ('402', 'Okra');
INSERT INTO ingredients (id, name) VALUES ('403', 'Oksekød');
INSERT INTO ingredients (id, name) VALUES ('404', 'Oksetalg');
INSERT INTO ingredients (id, name) VALUES ('405', 'Oliven');
INSERT INTO ingredients (id, name) VALUES ('406', 'Olivenolie');
INSERT INTO ingredients (id, name) VALUES ('407', 'Ost');
INSERT INTO ingredients (id, name) VALUES ('408', 'Pak choi');
INSERT INTO ingredients (id, name) VALUES ('409', 'Palmekerneolie');
INSERT INTO ingredients (id, name) VALUES ('410', 'Palmeolie');
INSERT INTO ingredients (id, name) VALUES ('411', 'Papaya');
INSERT INTO ingredients (id, name) VALUES ('412', 'Paradisæble');
INSERT INTO ingredients (id, name) VALUES ('413', 'Paranød');
INSERT INTO ingredients (id, name) VALUES ('414', 'Parmesan');
INSERT INTO ingredients (id, name) VALUES ('415', 'Passionsfrugt');
INSERT INTO ingredients (id, name) VALUES ('416', 'Pasta');
INSERT INTO ingredients (id, name) VALUES ('417', 'Pastiller');
INSERT INTO ingredients (id, name) VALUES ('418', 'Pastinak');
INSERT INTO ingredients (id, name) VALUES ('419', 'Paté');
INSERT INTO ingredients (id, name) VALUES ('420', 'Peanuts');
INSERT INTO ingredients (id, name) VALUES ('421', 'Peber');
INSERT INTO ingredients (id, name) VALUES ('422', 'Peberfrugt');
INSERT INTO ingredients (id, name) VALUES ('423', 'Peberrod');
INSERT INTO ingredients (id, name) VALUES ('424', 'Peberrodssalat');
INSERT INTO ingredients (id, name) VALUES ('425', 'Pecannød');
INSERT INTO ingredients (id, name) VALUES ('426', 'Pekannød');
INSERT INTO ingredients (id, name) VALUES ('427', 'Perlebyg');
INSERT INTO ingredients (id, name) VALUES ('428', 'Perleløg');
INSERT INTO ingredients (id, name) VALUES ('429', 'Perlespelt');
INSERT INTO ingredients (id, name) VALUES ('430', 'Persille');
INSERT INTO ingredients (id, name) VALUES ('431', 'Persillerod');
INSERT INTO ingredients (id, name) VALUES ('432', 'Pighvarre');
INSERT INTO ingredients (id, name) VALUES ('433', 'Pilsner');
INSERT INTO ingredients (id, name) VALUES ('434', 'Pindeis');
INSERT INTO ingredients (id, name) VALUES ('435', 'Pinjekerner');
INSERT INTO ingredients (id, name) VALUES ('436', 'Pistacienød');
INSERT INTO ingredients (id, name) VALUES ('437', 'Plantemargarine');
INSERT INTO ingredients (id, name) VALUES ('438', 'Pomelo');
INSERT INTO ingredients (id, name) VALUES ('439', 'Pommes frites');
INSERT INTO ingredients (id, name) VALUES ('440', 'Pop Corn');
INSERT INTO ingredients (id, name) VALUES ('441', 'Pop corn');
INSERT INTO ingredients (id, name) VALUES ('442', 'Porre');
INSERT INTO ingredients (id, name) VALUES ('443', 'Porrer');
INSERT INTO ingredients (id, name) VALUES ('444', 'Porter/Stout');
INSERT INTO ingredients (id, name) VALUES ('445', 'Portvin');
INSERT INTO ingredients (id, name) VALUES ('446', 'Poulard');
INSERT INTO ingredients (id, name) VALUES ('447', 'Pumpernikkel');
INSERT INTO ingredients (id, name) VALUES ('448', 'Purløg');
INSERT INTO ingredients (id, name) VALUES ('449', 'Pære');
INSERT INTO ingredients (id, name) VALUES ('450', 'Pærecider');
INSERT INTO ingredients (id, name) VALUES ('451', 'Pølse');
INSERT INTO ingredients (id, name) VALUES ('452', 'Pølsebrød');
INSERT INTO ingredients (id, name) VALUES ('453', 'Quinoa');
INSERT INTO ingredients (id, name) VALUES ('454', 'Rabarber');
INSERT INTO ingredients (id, name) VALUES ('455', 'Radise');
INSERT INTO ingredients (id, name) VALUES ('456', 'Rapsolie');
INSERT INTO ingredients (id, name) VALUES ('457', 'Rasp');
INSERT INTO ingredients (id, name) VALUES ('458', 'Reje');
INSERT INTO ingredients (id, name) VALUES ('459', 'Rejeost');
INSERT INTO ingredients (id, name) VALUES ('460', 'Remoulade');
INSERT INTO ingredients (id, name) VALUES ('461', 'Ribbensstegssandwich');
INSERT INTO ingredients (id, name) VALUES ('462', 'Ribs');
INSERT INTO ingredients (id, name) VALUES ('463', 'Ribsgele');
INSERT INTO ingredients (id, name) VALUES ('464', 'Ribssaft');
INSERT INTO ingredients (id, name) VALUES ('465', 'Rice');
INSERT INTO ingredients (id, name) VALUES ('466', 'Ris');
INSERT INTO ingredients (id, name) VALUES ('467', 'Risdrik');
INSERT INTO ingredients (id, name) VALUES ('468', 'Risengryn');
INSERT INTO ingredients (id, name) VALUES ('469', 'Riskiks/riskage');
INSERT INTO ingredients (id, name) VALUES ('470', 'Risklid');
INSERT INTO ingredients (id, name) VALUES ('471', 'Rismel');
INSERT INTO ingredients (id, name) VALUES ('472', 'Risstivelse');
INSERT INTO ingredients (id, name) VALUES ('473', 'Roastbeef');
INSERT INTO ingredients (id, name) VALUES ('474', 'Rodfrugter');
INSERT INTO ingredients (id, name) VALUES ('475', 'Rodfrugtfritter');
INSERT INTO ingredients (id, name) VALUES ('476', 'Rom');
INSERT INTO ingredients (id, name) VALUES ('477', 'Roquefort');
INSERT INTO ingredients (id, name) VALUES ('478', 'Rosenkål');
INSERT INTO ingredients (id, name) VALUES ('479', 'Rosévin');
INSERT INTO ingredients (id, name) VALUES ('480', 'Roulade');
INSERT INTO ingredients (id, name) VALUES ('481', 'Rucola');
INSERT INTO ingredients (id, name) VALUES ('482', 'Rugbrød');
INSERT INTO ingredients (id, name) VALUES ('483', 'Rugkerner');
INSERT INTO ingredients (id, name) VALUES ('484', 'Rugmel');
INSERT INTO ingredients (id, name) VALUES ('485', 'Rugsigtemel');
INSERT INTO ingredients (id, name) VALUES ('486', 'Rullepølse');
INSERT INTO ingredients (id, name) VALUES ('487', 'Rundstykke');
INSERT INTO ingredients (id, name) VALUES ('488', 'Rygeost');
INSERT INTO ingredients (id, name) VALUES ('489', 'Rype');
INSERT INTO ingredients (id, name) VALUES ('490', 'Ræddike');
INSERT INTO ingredients (id, name) VALUES ('491', 'Rødbede');
INSERT INTO ingredients (id, name) VALUES ('492', 'Rødfisk');
INSERT INTO ingredients (id, name) VALUES ('493', 'Rødkål');
INSERT INTO ingredients (id, name) VALUES ('494', 'Rødspætte');
INSERT INTO ingredients (id, name) VALUES ('495', 'Rødtunge');
INSERT INTO ingredients (id, name) VALUES ('496', 'Rødvin');
INSERT INTO ingredients (id, name) VALUES ('497', 'Sagogryn');
INSERT INTO ingredients (id, name) VALUES ('498', 'Sakkarin');
INSERT INTO ingredients (id, name) VALUES ('499', 'Salami');
INSERT INTO ingredients (id, name) VALUES ('500', 'Salat');
INSERT INTO ingredients (id, name) VALUES ('501', 'Salt');
INSERT INTO ingredients (id, name) VALUES ('502', 'Salt kød');
INSERT INTO ingredients (id, name) VALUES ('503', 'Samsø');
INSERT INTO ingredients (id, name) VALUES ('504', 'Sandart');
INSERT INTO ingredients (id, name) VALUES ('505', 'Sapodille');
INSERT INTO ingredients (id, name) VALUES ('506', 'Sapote');
INSERT INTO ingredients (id, name) VALUES ('507', 'Sardin');
INSERT INTO ingredients (id, name) VALUES ('508', 'Sauce');
INSERT INTO ingredients (id, name) VALUES ('509', 'Savoykål');
INSERT INTO ingredients (id, name) VALUES ('510', 'Seitan');
INSERT INTO ingredients (id, name) VALUES ('511', 'Sej');
INSERT INTO ingredients (id, name) VALUES ('512', 'Selleri');
INSERT INTO ingredients (id, name) VALUES ('513', 'Sennep');
INSERT INTO ingredients (id, name) VALUES ('514', 'Sesamfrø');
INSERT INTO ingredients (id, name) VALUES ('515', 'Sesamolie');
INSERT INTO ingredients (id, name) VALUES ('516', 'Shawarma kebabkød');
INSERT INTO ingredients (id, name) VALUES ('517', 'Sherry');
INSERT INTO ingredients (id, name) VALUES ('518', 'Sigtebrød');
INSERT INTO ingredients (id, name) VALUES ('519', 'Sigtemel');
INSERT INTO ingredients (id, name) VALUES ('520', 'Sild');
INSERT INTO ingredients (id, name) VALUES ('521', 'Sildepostej');
INSERT INTO ingredients (id, name) VALUES ('522', 'Sirup');
INSERT INTO ingredients (id, name) VALUES ('523', 'Skaldyrssalat');
INSERT INTO ingredients (id, name) VALUES ('524', 'Skinke');
INSERT INTO ingredients (id, name) VALUES ('525', 'Skinkeost 30+');
INSERT INTO ingredients (id, name) VALUES ('526', 'Skinkepølse');
INSERT INTO ingredients (id, name) VALUES ('527', 'Skinkesalat');
INSERT INTO ingredients (id, name) VALUES ('528', 'Skorzonerrod');
INSERT INTO ingredients (id, name) VALUES ('529', 'Skrubbe');
INSERT INTO ingredients (id, name) VALUES ('530', 'Skumfiduser');
INSERT INTO ingredients (id, name) VALUES ('531', 'Skummetmælk');
INSERT INTO ingredients (id, name) VALUES ('532', 'Skummetmælksost');
INSERT INTO ingredients (id, name) VALUES ('533', 'Skummetmælkspulver');
INSERT INTO ingredients (id, name) VALUES ('534', 'Skyr');
INSERT INTO ingredients (id, name) VALUES ('535', 'Skærekage');
INSERT INTO ingredients (id, name) VALUES ('536', 'Skæreost');
INSERT INTO ingredients (id, name) VALUES ('537', 'Smelteost');
INSERT INTO ingredients (id, name) VALUES ('538', 'Småkage');
INSERT INTO ingredients (id, name) VALUES ('539', 'Smør');
INSERT INTO ingredients (id, name) VALUES ('540', 'Smørbart blandingsprodukt');
INSERT INTO ingredients (id, name) VALUES ('541', 'Snacks');
INSERT INTO ingredients (id, name) VALUES ('542', 'Snaps');
INSERT INTO ingredients (id, name) VALUES ('543', 'Sodavand');
INSERT INTO ingredients (id, name) VALUES ('544', 'Soja sauce');
INSERT INTO ingredients (id, name) VALUES ('545', 'Sojabønner');
INSERT INTO ingredients (id, name) VALUES ('546', 'Sojadrik');
INSERT INTO ingredients (id, name) VALUES ('547', 'Sojamel');
INSERT INTO ingredients (id, name) VALUES ('548', 'Sojaolie');
INSERT INTO ingredients (id, name) VALUES ('549', 'Solbær');
INSERT INTO ingredients (id, name) VALUES ('550', 'Solbærgele');
INSERT INTO ingredients (id, name) VALUES ('551', 'Solbærmarmelade');
INSERT INTO ingredients (id, name) VALUES ('552', 'Solbærsaft');
INSERT INTO ingredients (id, name) VALUES ('553', 'Solsikkefrø');
INSERT INTO ingredients (id, name) VALUES ('554', 'Solsikkeolie');
INSERT INTO ingredients (id, name) VALUES ('555', 'Sorbetis');
INSERT INTO ingredients (id, name) VALUES ('556', 'Sorbitol');
INSERT INTO ingredients (id, name) VALUES ('557', 'Sortmund');
INSERT INTO ingredients (id, name) VALUES ('558', 'Spegepølse');
INSERT INTO ingredients (id, name) VALUES ('559', 'Spegesild');
INSERT INTO ingredients (id, name) VALUES ('560', 'Speltmel');
INSERT INTO ingredients (id, name) VALUES ('561', 'Sperling');
INSERT INTO ingredients (id, name) VALUES ('562', 'Spidskommen');
INSERT INTO ingredients (id, name) VALUES ('563', 'Spidskål');
INSERT INTO ingredients (id, name) VALUES ('564', 'Spinat');
INSERT INTO ingredients (id, name) VALUES ('565', 'Spirituosa');
INSERT INTO ingredients (id, name) VALUES ('566', 'Sprængt nakke');
INSERT INTO ingredients (id, name) VALUES ('567', 'Spædbørnsmad');
INSERT INTO ingredients (id, name) VALUES ('568', 'Squash');
INSERT INTO ingredients (id, name) VALUES ('569', 'Steak fries');
INSERT INTO ingredients (id, name) VALUES ('570', 'Stenbider');
INSERT INTO ingredients (id, name) VALUES ('571', 'Stikkelsbær');
INSERT INTO ingredients (id, name) VALUES ('572', 'Stjernefrugt');
INSERT INTO ingredients (id, name) VALUES ('573', 'Stykker');
INSERT INTO ingredients (id, name) VALUES ('574', 'Sukker');
INSERT INTO ingredients (id, name) VALUES ('575', 'Sukkerært');
INSERT INTO ingredients (id, name) VALUES ('576', 'Supperurter');
INSERT INTO ingredients (id, name) VALUES ('577', 'Surbrød');
INSERT INTO ingredients (id, name) VALUES ('578', 'Surbær');
INSERT INTO ingredients (id, name) VALUES ('579', 'Sushi');
INSERT INTO ingredients (id, name) VALUES ('580', 'Svenbo');
INSERT INTO ingredients (id, name) VALUES ('581', 'Sveske');
INSERT INTO ingredients (id, name) VALUES ('582', 'Sveskejuice');
INSERT INTO ingredients (id, name) VALUES ('583', 'Sylte');
INSERT INTO ingredients (id, name) VALUES ('584', 'Syltetøj');
INSERT INTO ingredients (id, name) VALUES ('585', 'Syre');
INSERT INTO ingredients (id, name) VALUES ('586', 'Syrnet fløde 9 %');
INSERT INTO ingredients (id, name) VALUES ('587', 'Sælkød');
INSERT INTO ingredients (id, name) VALUES ('588', 'Sødmælk');
INSERT INTO ingredients (id, name) VALUES ('589', 'Sødmælkspulver');
INSERT INTO ingredients (id, name) VALUES ('590', 'Søtunge');
INSERT INTO ingredients (id, name) VALUES ('591', 'Tahin');
INSERT INTO ingredients (id, name) VALUES ('592', 'Tamarind');
INSERT INTO ingredients (id, name) VALUES ('593', 'Tang');
INSERT INTO ingredients (id, name) VALUES ('594', 'Te');
INSERT INTO ingredients (id, name) VALUES ('595', 'Tebirkes');
INSERT INTO ingredients (id, name) VALUES ('596', 'Theboller o.l.');
INSERT INTO ingredients (id, name) VALUES ('597', 'Tidselolie');
INSERT INTO ingredients (id, name) VALUES ('598', 'Tigerreje');
INSERT INTO ingredients (id, name) VALUES ('599', 'Tofu');
INSERT INTO ingredients (id, name) VALUES ('600', 'Tomat');
INSERT INTO ingredients (id, name) VALUES ('601', 'Tomatjuice');
INSERT INTO ingredients (id, name) VALUES ('602', 'Tomatketchup');
INSERT INTO ingredients (id, name) VALUES ('603', 'Tomatpure');
INSERT INTO ingredients (id, name) VALUES ('604', 'Tomatsuppe');
INSERT INTO ingredients (id, name) VALUES ('605', 'Torsk');
INSERT INTO ingredients (id, name) VALUES ('606', 'Tranebær');
INSERT INTO ingredients (id, name) VALUES ('607', 'Tun');
INSERT INTO ingredients (id, name) VALUES ('608', 'Tunge');
INSERT INTO ingredients (id, name) VALUES ('609', 'Tungepølse');
INSERT INTO ingredients (id, name) VALUES ('610', 'Tunsalat');
INSERT INTO ingredients (id, name) VALUES ('611', 'Tvebakker');
INSERT INTO ingredients (id, name) VALUES ('612', 'Tyggegummi');
INSERT INTO ingredients (id, name) VALUES ('613', 'Tyttebær');
INSERT INTO ingredients (id, name) VALUES ('614', 'Tørkage');
INSERT INTO ingredients (id, name) VALUES ('615', 'Tørret skinke');
INSERT INTO ingredients (id, name) VALUES ('616', 'Vaffelis');
INSERT INTO ingredients (id, name) VALUES ('617', 'Vaffelrør');
INSERT INTO ingredients (id, name) VALUES ('618', 'Valle');
INSERT INTO ingredients (id, name) VALUES ('619', 'Valle protein pulver');
INSERT INTO ingredients (id, name) VALUES ('620', 'Vallepulver');
INSERT INTO ingredients (id, name) VALUES ('621', 'Valnød');
INSERT INTO ingredients (id, name) VALUES ('622', 'Valnøddeolie');
INSERT INTO ingredients (id, name) VALUES ('623', 'Vand');
INSERT INTO ingredients (id, name) VALUES ('624', 'Vandmelon');
INSERT INTO ingredients (id, name) VALUES ('625', 'Vanilje is');
INSERT INTO ingredients (id, name) VALUES ('626', 'Vekao');
INSERT INTO ingredients (id, name) VALUES ('627', 'Vermouth');
INSERT INTO ingredients (id, name) VALUES ('628', 'Vinbjergssnegle');
INSERT INTO ingredients (id, name) VALUES ('629', 'Vindrue');
INSERT INTO ingredients (id, name) VALUES ('630', 'Vindruekerneolie');
INSERT INTO ingredients (id, name) VALUES ('631', 'Vingummi');
INSERT INTO ingredients (id, name) VALUES ('632', 'Vodka');
INSERT INTO ingredients (id, name) VALUES ('633', 'Voksbønner');
INSERT INTO ingredients (id, name) VALUES ('634', 'Whisky');
INSERT INTO ingredients (id, name) VALUES ('635', 'Wienerbrød');
INSERT INTO ingredients (id, name) VALUES ('636', 'Wienerpølse');
INSERT INTO ingredients (id, name) VALUES ('637', 'Wokmix');
INSERT INTO ingredients (id, name) VALUES ('638', 'Yams');
INSERT INTO ingredients (id, name) VALUES ('639', 'Ylette naturel');
INSERT INTO ingredients (id, name) VALUES ('640', 'Ymer naturel');
INSERT INTO ingredients (id, name) VALUES ('641', 'Yoghurt');
INSERT INTO ingredients (id, name) VALUES ('642', 'Yoghurt naturel');
INSERT INTO ingredients (id, name) VALUES ('643', 'Ål');
INSERT INTO ingredients (id, name) VALUES ('644', 'Æble');
INSERT INTO ingredients (id, name) VALUES ('645', 'Æblecider');
INSERT INTO ingredients (id, name) VALUES ('646', 'Æblegele');
INSERT INTO ingredients (id, name) VALUES ('647', 'Æblejuice');
INSERT INTO ingredients (id, name) VALUES ('648', 'Æblemost');
INSERT INTO ingredients (id, name) VALUES ('649', 'Æg');
INSERT INTO ingredients (id, name) VALUES ('650', 'Æggesalat');
INSERT INTO ingredients (id, name) VALUES ('651', 'Ærter');
INSERT INTO ingredients (id, name) VALUES ('652', 'Ørred');
INSERT INTO ingredients (id, name) VALUES ('653', 'Østers');
-- +goose Down 
DELETE FROM ingredients;